### ISSUE TITLE
option to make xob instance quiet

### ISSUE THREAD

**Issue by mighty9245** [florentc/xob#15]
would be good to have a way to make xob quiet with -q or --quiet argument passed, so it won't print anything (currently prints on every update)

**Comment by florentc** [comment]
I agree. xob prints on every update so new users can be sure the input they provide works in case they do not see the bar because it is misplaced out of sight (e.g. on multihead setups) or too quick to vanish.

Which mode should xob defaults to? Quiet or verbose? I will keep this issue open a little while to gather opinions on the matter.

**Comment by mighty9245** [comment]
oh, yeah, there are two sides of this idea: either xob is verbose and quiet with -q (--quiet) or xob is quiet and verbose with -v (--verbose). i don't really care about this.

**Comment by abspython** [comment]
A temporary work-around is to use `tail -f /tmp/xobpipe | xob >/dev/null`.
